env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
  - simple-import-sort
rules:
  {
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
  }
