language: node_js
node_js:
- 8
- 9
- node
deploy:
  provider: npm
  email: alfred8844@gmail.com
  api_key:
    secure: NmXVk4WS3TVbmmrSvbaw6UW/g5Tmr/XyHG8d9rL1c3WFMgwmyGX8/C32ETUhsu59dArDfuKf+xpPGYO7M6Q7sxv/mpgG5IDPc1d+92L6adCnaZR0KPs6IG0Kf9Mp2LrLijsVwuyOq/ErW/Nzm2QohAbJplstEI713UrO9CPIr1O3Xpbsit0i9c5TOIef/ZqwBfISJpZsqWdwHfxuTrkPRvchV0ijdgo5s25NEwSGkxJ0NyHDppkrUCDvcoTBNN6onGWBH0uqAIapyYJOISruWpZ8NVwICZFtbKgq6C7hjThoyOC2/ICPXp+nNfeGQi+D/Yz6Tr5K/la3HQVus9GRmjMwJ/nrKu5S8wtpya5lInCBV2BR0m8OLl+60P4LZTavqfJBVUm/4PrKvRB18P+uppuNQDAoUweWKhTbiVY444MPZ7+zyR8KkyrSnUZotkeZXKYtPX6o46m5A0VtBL0xa3MKsRIRuTwiV9xBPbXbI3v8p1a/J6xXB1SnO1gSy3CtbWUO6bVd/19FTWAYc1pyhGJ4oOd9RxOlNM284dyTe6HzIwDYZVCvMBp3LIPlrMzSHVHPieEe738vFVhijEk2ldZyzWDwKBJQqJGi2lHA7Z185yZwsO1enWrCOB9GlH+OCP6pA10KSwZXUBfW5dVQ8uBINOX5vBwc0cOPVbL9/4k=
  on:
    tags: true
    repo: achankf/myalgo-ts
